FROM 607182506347.dkr.ecr.us-east-1.amazonaws.com/model_server:detectron_base
RUN perl -pi -e 's/\[\"requested_revision\"\]/.get\(\"requested_revision\"\)/' .local/share/pypoetry/venv/lib/python3.8/site-packages/poetry/repositories/installed_repository.py
COPY pyproject.toml .
RUN poetry config virtualenvs.options.system-site-packages true --local
RUN poetry install
RUN pip install 'git+https://github.com/facebookresearch/detectron2.git'
COPY --chown=appuser:sudo fastapi_poc .
